per_listener_settings false
allow_anonymous false
acl_file /work/acl
log_dest stdout
log_type error
log_type warning
listener 8883
cafile /work/pki/ca.crt
certfile /work/pki/broker.crt
keyfile /work/pki/broker.key
tls_version tlsv1.3
require_certificate true
use_identity_as_username true
