per_listener_settings false
allow_anonymous false
acl_file /work/acl
log_dest file /tmp/mosq_8888.log
log_type error
log_type warning
log_type notice
log_type information
set_tcp_nodelay true
user root
max_packet_size 300000
listener 8888
cafile /work/pki/ca.crt
certfile /work/pki/broker.crt
keyfile /work/pki/broker.key
tls_version tlsv1.3
require_certificate true
use_identity_as_username true
