"""Mutation check (IMPLEMENTATION-ROADMAP §14, C1-9): each mutant disables ONE security or correctness check in pqgrid;
the in-process suite (tests/unit, tests/security) must kill it. A survivor is either a missing test or an equivalent
mutant (a check made redundant by construction: record why).

Run inside the test image (tools/ is copied to /app/tools; no host mounts), 4 slices in parallel:
    for k in 0 1 2 3; do docker run --rm pqgrid-tests python tools/mutation_check.py --root /app $k 4 & done; wait
    docker run --rm pqgrid-tests python tools/mutation_check.py --root /app sel 1,9,10 0 1   # only these mutants
A mutant counts as KILLED only when a test FAILED (pytest exit code 1); a crash or collection error is ERROR.
Mutants 117-139 disable the checks added by cycle 1 (C2-2), 140-143 cycle 2's (C2-8), 144-146 cycle 3's (C3-4),
147-172 the remediation after the independent release audit (R-x), 173-182 the fix of the Codex audit's P1-2,
183-200 its other fixes, 201-215 the fixes of the second Codex review, 216-222 the follow-up, 223-231 the third
review (§16). A mutant may name broker tests (5th element) for a check only a real broker exercises; they run in
addition to the in-process suite (the test image has Mosquitto). Results and the classification of every survivor:
IMPLEMENTATION-ROADMAP §15 (§16 from 173 on).
"""
import os
import shutil
import subprocess
import sys
import tempfile

M = [
    # ---------------------------------------------------------------- handshake (utility)
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(did, topic_id):\n", "        if False:\n", "CH identity = topic"),
    ("pqgrid/e2e/handshake.py", "        if dclass != rec.dclass.encode():\n", "        if False:\n", "CH class = registry"),
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(pinfo, self.policy.info()):\n            raise PolicyMismatchError",
     "        if False:\n            raise PolicyMismatchError", "CH POLICY_INFO current"),
    ("pqgrid/e2e/handshake.py", "        if tag != b\"DF\" or not ct_eq(keys.mac_d(pend.kc_d, pend.th2, pend.mu, bundle), mac_d_rx):",
     "        if tag != b\"DF\":", "DF MAC_D"),
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(s.policy_info, self.policy.info()):                    # M1",
     "        if False:                    # M1", "DF M1 policy race"),
    ("pqgrid/e2e/handshake.py", "        if now >= s.chain_expires:                                            # M2",
     "        if False:                                            # M2", "DF M2 chain end"),
    ("pqgrid/e2e/handshake.py", "        if not self.active(who.encode()):", "        if False:", "alert: revoked device"),
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(s.policy_info, self.policy.info()):\n            raise EnvelopeError(\"session belongs",
     "        if False:\n            raise EnvelopeError(\"session belongs", "alert: old-policy session"),
    ("pqgrid/e2e/handshake.py", "        if self.now() < s.chain_expires:\n            return False\n        if self.sessions",
     "        if True:\n            return False\n        if self.sessions", "utility chain end"),
    ("pqgrid/e2e/handshake.py", "        if (s is None or rec is None or not rec.active or s.dclass != rec.dclass",
     "        if (s is None or rec is None or s.dclass != rec.dclass", "current_session: revoked"),
    ("pqgrid/e2e/handshake.py", "        self._pending.pop(device_id, None)\n        return closed",
     "        return closed", "revoke: half-open kept"),
    # ---------------------------------------------------------------- handshake (device)
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(pinfo_u, self.policy.info()):", "        if False:", "SH POLICY_INFO"),
    ("pqgrid/e2e/handshake.py", "        if mode_b != self.profile.resume.value.encode():", "        if False:", "SH resume mode"),
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(keys.mac_u(mk.kc_u, th2), mu):", "        if False:", "SH MAC_U"),
    ("pqgrid/e2e/handshake.py", "        if not ct_eq(keys.mac_u(mk.kc_u, th), mu):", "        if False:", "RS MAC_U"),
    ("pqgrid/e2e/handshake.py", "            elif ct_e:\n                raise HandshakeError(\"resume reply failed authentication\")",
     "            elif False:\n                raise HandshakeError(\"resume reply failed authentication\")", "RS PSK with ct"),
    ("pqgrid/e2e/handshake.py", "        elif tag != b\"FIN\" or not ct_eq(m, mac(keys.fin_key(s.k_master), s.sid)):",
     "        elif tag != b\"FIN\":", "FIN MAC"),
    ("pqgrid/e2e/handshake.py", "            if s.resume_mode is ResumeMode.NONE:\n                raise HandshakeError(\"unexpected ticket",
     "            if False:\n                raise HandshakeError(\"unexpected ticket", "NT for NONE class"),
    ("pqgrid/e2e/handshake.py", "        if tag != b\"\\x07\" or self.session is None or not ct_eq(sid, self.session.sid):",
     "        if tag != b\"\\x07\" or self.session is None:", "resync hint sid"),
    ("pqgrid/e2e/handshake.py", "        if self.clock() - self._last_resync < self.RESYNC_INTERVAL_S:\n            return False",
     "        if False:\n            return False", "resync hint rate"),
    ("pqgrid/e2e/handshake.py", "        s = self.session\n        if s is None or self.now() < s.chain_expires:",
     "        s = self.session\n        if True:", "device chain end"),
    # ---------------------------------------------------------------- tickets
    ("pqgrid/pasr/tickets.py", "        if not (ct_eq(t.device_id, topic_id) and ct_eq(t.device_id, claimed_id)):",
     "        if not ct_eq(t.device_id, claimed_id):", "ticket check 3 topic"),
    ("pqgrid/pasr/tickets.py", "        if rec is None or not rec.active:\n            raise TicketError(\"device unknown or revoked\")",
     "        if rec is None:\n            raise TicketError(\"device unknown or revoked\")", "ticket check 4 revoked"),
    ("pqgrid/pasr/tickets.py", "        if rec.dclass != t.dclass:", "        if False:", "ticket check 4 class"),
    ("pqgrid/pasr/tickets.py", "        if not (now < t.expires_at and now < t.chain_expires_at):",
     "        if not (now < t.expires_at):", "ticket check 5 chain"),
    ("pqgrid/pasr/tickets.py", "        if not (now < t.expires_at and now < t.chain_expires_at):",
     "        if not (now < t.chain_expires_at):", "ticket check 5 ticket"),
    ("pqgrid/pasr/tickets.py", "        if not (ct_eq(t.policy_info, policy_info) and ct_eq(policy_info, policy.info())):",
     "        if not ct_eq(t.policy_info, policy_info):", "ticket check 6 current"),
    ("pqgrid/pasr/tickets.py", "        if t.fw_version != fw_version:", "        if False:", "ticket check 7 fw"),
    ("pqgrid/pasr/tickets.py", "        if not (mode == t.resume_mode.value.encode() and t.resume_mode is current",
     "        if not (mode == t.resume_mode.value.encode()", "ticket check 8 current mode"),
    ("pqgrid/pasr/tickets.py", "        if len(pk_e) != (hkem.PK_LEN if current is ResumeMode.PSK_KEM else 0):",
     "        if False:", "ticket check 8 fresh key"),
    ("pqgrid/pasr/tickets.py", "        if not ct_eq(mac(keys.binder_key(t.psk), binder_input), binder):",
     "        if False:", "ticket check 9 binder"),
    ("pqgrid/pasr/tickets.py", "        if not self.used.consume(t.ticket_id, t.expires_at, now):",
     "        if not (self.used.consume(t.ticket_id, t.expires_at, now) or True):", "ticket single use"),
    ("pqgrid/pasr/stek.py", "        if k is None or now >= k.retire_at:", "        if k is None:", "STEK retirement"),
    # ---------------------------------------------------------------- envelopes
    ("pqgrid/e2e/envelopes.py", "    if parts[1] != s.dclass or parts[2].encode() != s.device_id:\n        raise EnvelopeError(\"envelope belongs to another device's session\")\n\n\ndef seal_alert",
     "    if False:\n        raise EnvelopeError(\"envelope belongs to another device's session\")\n\n\ndef seal_alert", "alert ownership"),
    ("pqgrid/e2e/envelopes.py", "    if policy.tier(topic) is not Tier.ALERT:", "    if False:", "alert tier"),
    ("pqgrid/e2e/envelopes.py", "    if parts[1] != s.dclass or parts[2].encode() != s.device_id:\n        raise EnvelopeError(\"envelope belongs to another device's session\")\n\n\ndef seal_control",
     "    if False:\n        raise EnvelopeError(\"envelope belongs to another device's session\")\n\n\ndef seal_control", "control ownership"),
    ("pqgrid/e2e/envelopes.py", "    if policy.tier(topic) is not Tier.CONTROL:\n        raise EnvelopeError(\"topic is not CONTROL",
     "    if False:\n        raise EnvelopeError(\"topic is not CONTROL", "control tier"),
    ("pqgrid/e2e/envelopes.py", "    if not ct_eq(m, mac(s.key(\"ACK\", \"down\"), sid + seq_b)):", "    if False:", "alert ACK MAC"),
    ("pqgrid/e2e/envelopes.py", "    if not ct_eq(m, mac(s.key(\"ACK\", \"up\"), sid + mseq_b + cseq_b + status)):", "    if False:", "status ACK MAC"),
    ("pqgrid/e2e/envelopes.py", "    if not ct_eq(m, mac(s.key(\"SYNC\", \"up\"), sid + seq_b + epoch_b + zone_b)):", "    if False:", "zone sync MAC"),
    ("pqgrid/e2e/envelopes.py", "    guard = s.guard(\"SYNC\", \"up\")\n    guard.validate(seq)", "    guard = s.guard(\"SYNC\", \"up\")", "zone sync replay (phase1)"),
    ("pqgrid/e2e/envelopes.py", "    guard.accept(seq)\n    return zone, epoch", "    return zone, epoch", "zone sync replay (accept)"),
    ("pqgrid/e2e/envelopes.py", "    guard.accept(seq)                                     # phase 2: only after authentication",
     "    pass", "alert replay accept"),
    ("pqgrid/e2e/envelopes.py", "    guard.accept(seq)\n    return pt, seq", "    return pt, seq", "control replay accept"),
    ("pqgrid/e2e/envelopes.py", "    guard.validate(seq)                                   # phase 1: before decryption\n",
     "    guard.accept(seq)                                   # MUTANT: burn before auth\n", "alert two-phase (I-7)"),
    ("pqgrid/e2e/envelopes.py", "    guard = s.guard(\"CONTROL\", \"down\")\n    guard.validate(seq)",
     "    guard = s.guard(\"CONTROL\", \"down\")\n    guard.accept(seq)", "control two-phase (I-7)"),
    ("pqgrid/e2e/envelopes.py", "    if not valid_status(status):\n        raise EnvelopeError(\"unknown status\")\n    return mseq",
     "    return mseq", "utility status token"),
    # ---------------------------------------------------------------- commands (device)
    ("pqgrid/commands/device.py", "        if not self._verify(c.sig, cmd_signed_input(", "        if False and not self._verify(c.sig, cmd_signed_input(", "CMD signature"),
    ("pqgrid/commands/device.py", "        if not self._verify(g.sig, grant_signed_input(self.d.id, topic, g)):", "        if False:", "GRANT signature"),
    ("pqgrid/commands/device.py", "        if not ct_eq(g.sid, s.sid):\n            return ack(b\"REJECTED:sid\")", "        if False:\n            return ack(b\"REJECTED:sid\")", "GRANT sid binding"),
    ("pqgrid/commands/device.py", "        if not self._allowed(CmdType.CMD):", "        if False:", "CMD allowed"),
    ("pqgrid/commands/device.py", "        if not self._allowed(CmdType.SETPOINT):", "        if False:", "SETPOINT allowed"),
    ("pqgrid/commands/device.py", "        if st.is_applied(c.cmd_seq):", "        if False:", "CMD DUP"),
    ("pqgrid/commands/device.py", "        if c.cmd_seq <= st.last_applied:", "        if False:", "CMD SUPERSEDED"),
    ("pqgrid/commands/device.py", "        if self.d.now() >= c.expires_at:\n            return ack(b\"EXPIRED\")", "        if False:\n            return ack(b\"EXPIRED\")", "CMD EXPIRED"),
    ("pqgrid/commands/device.py", "        if len(c.command) > MAX_COMMAND:", "        if False:", "CMD size"),
    ("pqgrid/commands/device.py", "        if g.target not in self.targets:", "        if False:", "GRANT target"),
    ("pqgrid/commands/device.py", "        if not (g.min <= g.max and 0 < g.max_rate <= self.d.profile.max_setpoint_rate):", "        if False:", "GRANT bounds"),
    ("pqgrid/commands/device.py", "        if not (g.not_before <= now < g.expires_at and now < sp.expires_at):", "        if not (now < g.expires_at and now < sp.expires_at):", "SETPOINT not_before"),
    ("pqgrid/commands/device.py", "        if not (g.not_before <= now < g.expires_at and now < sp.expires_at):", "        if not (g.not_before <= now < g.expires_at):", "SETPOINT own expiry"),
    ("pqgrid/commands/device.py", "        if not g.min <= sp.value <= g.max:", "        if False:", "SETPOINT bounds"),
    ("pqgrid/commands/device.py", "        if len(win) >= g.max_rate:", "        if False:", "SETPOINT rate"),
    ("pqgrid/commands/device.py", "        g = next((g for g in self._grants.values() if g.grant_id == sp.grant_id and ct_eq(g.sid, s.sid)), None)",
     "        g = next((g for g in self._grants.values() if g.grant_id == sp.grant_id), None)", "SETPOINT grant sid"),
    ("pqgrid/commands/device.py", "        if z.aead is not self.d.profile.aead:", "        if False:", "ZONEKEY aead"),
    ("pqgrid/commands/device.py", "        st.write_applied(c.cmd_seq)                               # APPLIED durable before \"OK\"\n        return ack(b\"OK\")",
     "        return ack(b\"OK\")", "CMD APPLIED durable"),
    ("pqgrid/commands/device.py", "        if r.idempotent and self.d.now() < r.expires_at and r.cmd_seq > self.state.last_applied:",
     "        if r.idempotent and r.cmd_seq > self.state.last_applied:", "recover: expiry"),
    ("pqgrid/commands/device.py", "        if r.idempotent and self.d.now() < r.expires_at and r.cmd_seq > self.state.last_applied:",
     "        if self.d.now() < r.expires_at and r.cmd_seq > self.state.last_applied:", "recover: idempotent"),
    # ---------------------------------------------------------------- commands (utility)
    ("pqgrid/commands/utility.py", "        if not self.u.active(s.device_id):", "        if False:", "status from revoked"),
    ("pqgrid/commands/utility.py", "        if not ct_eq(s.policy_info, self.u.policy.info()):               # P10", "        if False:  # P10", "status old policy"),
    ("pqgrid/commands/utility.py", "            if status in (b\"DUP\", b\"SUPERSEDED\") and q.sends == 1 and msg_seq != 0:",
     "            if False:", "regression alarm"),
    ("pqgrid/commands/utility.py", "        if not g.min <= value <= g.max:", "        if False:", "utility setpoint bounds"),
    ("pqgrid/commands/utility.py", "        if not (valid_token(target) and lo <= hi and 0 < max_rate <= prof.max_setpoint_rate):",
     "        if not (valid_token(target) and lo <= hi):", "utility grant rate cap"),
    ("pqgrid/commands/utility.py", "            if q.last_sid == s.sid:\n                continue", "            pass", "redeliver once per session"),
    # ---------------------------------------------------------------- zones
    ("pqgrid/commands/zones.py", "        if bseq <= self.state.zone_bseq.get(zone, 0):", "        if False:", "bcast bseq replay"),
    ("pqgrid/commands/zones.py", "        if self.d.now() >= exp:\n            raise EnvelopeError(\"broadcast expired\")", "        if False:\n            raise EnvelopeError(\"broadcast expired\")", "bcast expiry"),
    ("pqgrid/commands/zones.py", "        if not mldsa_verify(self.d.policy.utility_cmd_pk, sig, bcast_signed_input(zone, bseq, exp, event)):", "        if False:", "bcast signature"),
    ("pqgrid/commands/zones.py", "        if t != T_BCAST or topic != event_topic(zone, alg) or self.d.policy.tier(topic) is not Tier.CONTROL:",
     "        if t != T_BCAST:", "bcast topic binding"),
    ("pqgrid/commands/zones.py", "        if z is None or device_id not in z.members:\n            raise CommandError(\"zone sync from a device that is not a member\")",
     "        if z is None:\n            raise CommandError(\"zone sync from a device that is not a member\")", "zone sync membership"),
    ("pqgrid/commands/zones.py", "        if now - self._last_sync.get((device_id, name), -ZONE_SYNC_MIN_S) < ZONE_SYNC_MIN_S:", "        if False:", "zone sync rate"),
    ("pqgrid/commands/zones.py", "            out += [self._seal(z, alg, ev) for ev in z.events if ev.bseq > joined]",
     "            out += [self._seal(z, alg, ev) for ev in z.events]", "resend join point"),
    ("pqgrid/commands/zones.py", "        self._rotate(z, [alg])\n\n    def remove_member", "        self._save(z)\n\n    def remove_member", "join rotates"),
    ("pqgrid/commands/zones.py", "        z.members.pop(device_id, None)\n        self._rotate(z, list(z.groups))", "        z.members.pop(device_id, None)\n        self._save(z)", "removal rotates"),
    # ---------------------------------------------------------------- policy
    ("pqgrid/policy/validator.py", "    if p.default_tier is not Tier.CONTROL:", "    if False:", "rule 1"),
    ("pqgrid/policy/validator.py", "        if c.unicast_control and c.resume not in (ResumeMode.PSK_KEM, ResumeMode.NONE):", "        if False:", "rule 3"),
    ("pqgrid/policy/validator.py", "        if not 0 < c.ticket_lifetime_s <= c.max_chain_age_s <= SEVEN_DAYS:", "        if not 0 < c.ticket_lifetime_s <= c.max_chain_age_s:", "rule 4 cap"),
    ("pqgrid/policy/validator.py", "    if installed_version is not None and p.version <= installed_version:", "    if False:", "rule 5"),
    ("pqgrid/policy/validator.py", "        if CmdType.SETPOINT in c.cmd_types and CmdType.GRANT not in c.cmd_types:", "        if False:", "rule 6"),
    ("pqgrid/policy/validator.py", "        if c.fota_chunk_size <= 0 or c.fota_chunk_size + CHUNK_OVERHEAD > c.max_packet:", "        if c.fota_chunk_size <= 0:", "rule 7"),
    ("pqgrid/policy/validator.py", "        if c.dup_window_s < MIN_DUP_WINDOW_S or c.pending_ttl_s < MIN_PENDING_TTL_S:", "        if False:", "rule 9"),
    ("pqgrid/policy/validator.py", "    if not 1 <= len(p.ca_set) <= 2:", "    if False:", "rule 10"),
    ("pqgrid/policy/engine.py", "    return max(hits) if hits else Tier.CONTROL", "    return max(hits) if hits else Tier.TELEMETRY", "fail-safe default"),
    ("pqgrid/policy/engine.py", "    return max(hits) if hits else Tier.CONTROL", "    return hits[0] if hits else Tier.CONTROL", "strongest wins"),
    ("pqgrid/policy/codec.py", "    if len(class_list) != len(policy.classes) or encode_policy(policy) != bytes(raw):", "    if len(class_list) != len(policy.classes):", "canonical policy"),
    # ---------------------------------------------------------------- wire / crypto
    ("pqgrid/wire.py", "    if i != len(buf):\n        raise WireError(\"trailing bytes\")", "    pass", "no trailing bytes"),
    ("pqgrid/wire.py", "        if length > MAX_FIELD:\n            raise WireError(\"field too large\")\n        if i + length", "        if i + length", "field cap"),
    ("pqgrid/suite/hkem.py", "    return sha3_256(ss_m + ss_x + ct_x + pk_x + XWING_LABEL)", "    return sha3_256(ss_m + ss_x + XWING_LABEL)", "X-Wing binds ct/pk"),
    ("pqgrid/e2e/keys.py", "    return mac(kc_d, b\"D-finished\" + h(th2, mac_u_, h(bundle)))", "    return mac(kc_d, b\"D-finished\" + h(th2, mac_u_))", "DR-044 bundle in MAC_D"),
    ("pqgrid/registry.py", "            self._store(rec)                                   # revocation is durable before it takes effect\n",
     "", "revocation durable"),
    # ---------------------------------------------------------------- persistence
    ("pqgrid/persistence/flash.py", "                if crc_at + 4 > len(data) or zlib.crc32(data[off:crc_at]) != struct.unpack_from(\">I\", data, crc_at)[0]:",
     "                if crc_at + 4 > len(data):", "record CRC"),
    ("pqgrid/persistence/device.py", "            if self.is_applied(seq):\n                store.delete(T_INTENT, key)", "            if False:\n                store.delete(T_INTENT, key)", "boot reconciliation"),
    ("pqgrid/persistence/device.py", "    def write_pending(self, c) -> None:\n        super().write_pending(c)\n        self._s.put(",
     "    def write_pending(self, c) -> None:\n        super().write_pending(c)\n        return\n        self._s.put(", "PENDING durable"),
    ("pqgrid/persistence/utility_db.py", "        c.execute(\"INSERT OR REPLACE INTO device_seq VALUES (?, ?)\", (device_id, n))", "        pass", "cmd counter persisted"),
    ("pqgrid/persistence/utility_db.py", "            self.db.execute(\"INSERT INTO used_tickets VALUES (?, ?)\", (ticket_id, expires_at))",
     "            pass", "used ticket persisted"),
    # ---------------------------------------------------------------- FOTA
    ("pqgrid/fota/installer.py", "        if not slh_verify(self.anchors[m.signer_anchor_id], sig, raw):", "        if False:", "manifest signature"),
    ("pqgrid/fota/installer.py", "        if m.device_class != self.cls:", "        if False:", "F7 class"),
    ("pqgrid/fota/installer.py", "        if m.version <= self.prot.committed[m.type]:\n            raise FotaError(\"rollback: version not newer than installed\")",
     "        if False:\n            raise FotaError(\"rollback: version not newer than installed\")", "anti-rollback (signed)"),
    ("pqgrid/fota/installer.py", "        if not merkle.verify(i, m.chunk_count, data, path, m.merkle_root):", "        if False:", "chunk Merkle"),
    ("pqgrid/fota/installer.py", "        if hashlib.sha256(image).digest() != m.payload_sha256:", "        if False:", "boot re-hash"),
    ("pqgrid/fota/installer.py", "        if not self_test(image):", "        if False:", "self-test"),
    ("pqgrid/fota/installer.py", "        if self.clock() < m.activate_at:\n            return \"waiting for activate_at\"", "        if False:\n            return \"waiting for activate_at\"", "fw activate_at"),
    ("pqgrid/fota/installer.py", "        if not (set(self.anchors) - self.prot.revoked - {rid}):", "        if False:", "last anchor"),
    ("pqgrid/fota/artifact.py", "    elif signer != release_anchor(revoked):", "    elif False:", "DR-050 release role"),
    ("pqgrid/fota/merkle.py", "    return sn == 0 and r == expected_root", "    return r == expected_root", "merkle sn==0"),
    ("pqgrid/fota/policy_artifact.py", "    if m.type != POLICY:", "    if False:", "policy artifact type"),
    ("pqgrid/fota/policy_artifact.py", "    if p.version != m.version or p.activate_at != m.activate_at:", "    if False:", "policy/manifest agree"),
    # ---------------------------------------------------------------- broker / ACL
    ("pqgrid/mqtt/broker.py", "        if not rec.active:\n            continue", "        if False:\n            continue", "ACL revoked"),
    ("pqgrid/mqtt/broker.py", "    if glob.get(\"allow_anonymous\") != \"false\":", "    if False:", "config anonymous"),
    # ---------------------------------------------------------------- checks added by cycle 1 (C1-x)
    ("pqgrid/fota/installer.py", "        if hashlib.sha256(payload).digest() != m.payload_sha256:          # as V-F4",
     "        if False:          # as V-F4", "C1-8 staged policy re-hash"),
    ("pqgrid/fota/installer.py", "        if hashlib.sha256(raw).digest() != digest:", "        if False:", "C1-8 installed policy digest"),
    ("pqgrid/fota/installer.py", "            return self.flash.policy_areas[1 - self.prot.policy[0]]",
     "            return self.flash.policy_areas[self.prot.policy[0]]", "C1-8 stage beside the installed policy"),
    ("pqgrid/fota/installer.py", "        self.prot.commit(POLICY, m.version, policy=(1 - self.prot.policy[0], m.payload_length, m.payload_sha256))",
     "        self.prot.commit(POLICY, m.version)", "C1-8 commit records the installed policy"),
    ("pqgrid/fota/installer.py", "            p.profile(self.cls)                                            # it must",
     "            pass                                            # it must", "C1-10 policy defines own class"),
    ("pqgrid/fota/installer.py", "        self.max_packet = p.profile(self.cls).max_packet                   # E61 now",
     "        pass                   # E61 now", "C1-10 installer limit follows commit"),
    ("pqgrid/fota/installer.py", "            self.max_packet = installed.profile(self.cls).max_packet\n",
     "            pass\n", "C1-10 installer limit at boot"),
    ("pqgrid/fota/installer.py", "        self._finish_interrupted_commits()                             # by the committed versions (trusted)\n",
     "", "C1-7 boot reconciliation"),
    ("pqgrid/mqtt/device_node.py", "            self.outbox.cap = prof.outbox_cap                 # the budget",
     "            pass                 # the budget", "C1-10 outbox cap follows policy"),
    ("pqgrid/commands/utility.py", "        self._forget_grants(device_id, s.sid, now)\n", "", "C1-4 GRANT pruning"),
    ("pqgrid/mqtt/utility_node.py", "                self._forget_scheduled()\n                self.refused.append",
     "                self.refused.append", "C1-3 refused schedule dropped"),
    ("pqgrid/mqtt/utility_node.py", "        validate(p, installed_version=self.n.endpoint.policy.version)  # … and so is one that is not newer",
     "        pass  # … and so is one that is not newer", "C1-3 schedule validates version"),
    ("pqgrid/mqtt/utility_node.py", "            self.n.db.save_policy(\"active\", signed, payload, anchors, revoked)   # active; durable",
     "            pass   # active; durable", "C1-12 active policy persisted"),
    ("pqgrid/mqtt/utility_node.py", "        self.n.db.save_policy(\"scheduled\", signed, payload, anchors, revoked)   # survives",
     "        pass   # survives", "C1-12 scheduled policy persisted"),
    ("pqgrid/persistence/utility_db.py", "        if active.version > policy.version:\n            policy = active",
     "        if False:\n            policy = active", "C1-12 active policy resumed"),
    ("pqgrid/fota/publisher.py", "            self._store(key, art, pub)                             # told",
     "            pass                             # told", "C1-13 publish persisted"),
    ("pqgrid/fota/publisher.py", "            self._store_revoked(rid)", "            pass", "C1-13 revocation persisted"),
    ("pqgrid/fota/publisher.py", "                    self._store(key, pub.artifact, None)           # still the newest",
     "                    pass           # still the newest", "C1-13 cleanup persisted"),
    ("pqgrid/persistence/flash.py", "                    end = (i + 1, 0)                           # after its type byte",
     "                    pass                           # after its type byte", "C1-1 torn header"),
    ("pqgrid/registry.py", "    return bool(_DEVICE_ID.fullmatch(device_id))", "    return bool(_DEVICE_ID.match(device_id))",
     "C1-2 device id fullmatch"),
    ("pqgrid/commands/codec.py", "    return bool(_TOKEN.fullmatch(s))", "    return bool(_TOKEN.match(s))", "C1-2 token fullmatch"),
    ("pqgrid/policy/validator.py", "    if not _POLICY_ID.fullmatch(p.policy_id):", "    if not _POLICY_ID.match(p.policy_id):",
     "C1-2 policy id fullmatch"),
    ("pqgrid/policy/validator.py", "        if not _CLASS_NAME.fullmatch(name) or c.name != name:",
     "        if not _CLASS_NAME.match(name) or c.name != name:", "C1-2 class name fullmatch"),
    # ---------------------------------------------------------------- checks added by cycle 2 (C2-x)
    ("pqgrid/commands/zones.py", "        self._finish_revocations()\n", "", "C2-4 revoked members leave at start"),
    ("pqgrid/mqtt/utility_node.py",
     "            self.n.zones.rotate_all()                                # first: a crash then leaves the old policy\n"
     "            self.n.db.save_policy(\"active\", signed, payload, anchors, revoked)   # active; durable before effect\n",
     "            self.n.db.save_policy(\"active\", signed, payload, anchors, revoked)   # active; durable before effect\n"
     "            self.n.zones.rotate_all()                                # first: a crash then leaves the old policy\n",
     "C2-5 rotate before persisting"),
    ("pqgrid/e2e/handshake.py",
     "            opened.append((aid, payload))\n",
     "            opened.append((aid, payload)); self._dedup(s.device_id, aid)\n", "C2-6 dedup after the reply"),
    ("pqgrid/mqtt/utility_node.py", "                    if rec is None or not rec.active or rec.dclass != cls:   # not wait",
     "                    if rec is None:   # not wait", "C2-7 telemetry from revoked devices"),
    # ---------------------------------------------------------------- checks added by cycle 3 (C3-x)
    ("pqgrid/mqtt/broker.py", "        if rec.dclass not in policy.classes:                      # it could not",
     "        if False:                      # it could not", "C3-1 no rights for an undefined class"),
    ("pqgrid/mqtt/device_node.py", "        if old:                                               # a policy moved",
     "        if False:                                               # a policy moved", "C3-3 leave the old group"),
    ("pqgrid/mqtt/device_node.py",
     "            want = {topics.dr_event(z, self.d.profile.aead) for z in self._zones}\n            new, old",
     "            want = self._dr_topics | {topics.dr_event(z, self.d.profile.aead) for z in self._zones\n"
     "                                      if not any(t.split('/')[2] == z for t in self._dr_topics)}\n            new, old",
     "C3-3 follow the new group (old rule: new zone names only)"),
    # ------------------------------------------------ remediation after the independent release audit (R-x)
    ("pqgrid/mqtt/utility_node.py", "        self.n.keyring.keys_for(p)                                     # … or whose",
     "        pass                                     # … or whose", "R H-1 schedule refuses keys not held"),
    ("pqgrid/mqtt/utility_node.py", "            self.n.endpoint.install_policy(p, static=static)",
     "            self.n.endpoint.install_policy(p)", "R H-1 activation switches the E2E key"),
    ("pqgrid/mqtt/utility_node.py", "            self.n.commands.cmd_key = cmd_key ",
     "            self.n.commands.cmd_key = self.n.commands.cmd_key ", "R H-1 activation switches the command key"),
    ("pqgrid/persistence/utility_db.py", "    static, cmd_key = keyring.keys_for(policy)\n", "",
     "R H-1 a restart takes the keys the active policy names"),
    ("pqgrid/commands/utility.py", "            if not mldsa_verify(self.u.policy.utility_cmd_pk, c.sig, signed):",
     "            if False:", "R H-1 queued commands re-signed after a rotation"),
    ("pqgrid/commands/zones.py", "        if not mldsa_verify(self.svc.u.policy.utility_cmd_pk, ev.sig, signed):",
     "        if False:", "R H-1 retained DR events re-signed after a rotation"),
    ("pqgrid/e2e/handshake.py", "            if not ct_eq(pinfo, self.policy.info()):\n                raise PolicyMismatchError(\"POLICY_INFO mismatch: the client",
     "            if False:\n                raise PolicyMismatchError(\"POLICY_INFO mismatch: the client",
     "R H-1 old-policy hello under a retired key recognised"),
    ("pqgrid/mqtt/device_node.py",
     "        return self._declared is not None and (self._declared != self._connect_props(self.d.profile)",
     "        return False and (self._declared != self._connect_props(self.d.profile)",
     "R H-2 reconnect when CONNECT properties change",
     ("tests/integration/test_connect_properties.py",)),
    ("pqgrid/mqtt/device_node.py", "            self._fota_subscribed = False                     # retained artifacts dropped",
     "            pass                     # retained artifacts dropped", "R H-2 re-subscribe after a raised limit",
     ("tests/integration/test_connect_properties.py",)),
    ("pqgrid/fota/publisher.py", "            return min(cur, self.floor.get(m.device_class, cur))",
     "            return cur", "R H-2 POLICY/KEYREVOKE sized to the class floor"),
    ("pqgrid/mqtt/utility_node.py", "        revoked = self.revoked_anchors() | set(revoked)             # M-1",
     "        revoked = set(revoked)             # M-1", "R M-1 activation uses the revocations of now"),
    ("pqgrid/mqtt/utility_node.py", "        revoked = frozenset(self.revoked_anchors() | set(revoked))    # M-1",
     "        revoked = frozenset(revoked)    # M-1", "R M-1 scheduling uses the revocations of now"),
    ("pqgrid/mqtt/utility_node.py", "        self._recheck_scheduled()                                      # M-1",
     "        pass                                      # M-1", "R M-1 a restart re-checks the scheduled policy"),
    ("pqgrid/e2e/handshake.py", "        self._refuse_if_stale(\"server hello\")               # DR-053",
     "        pass               # DR-053", "R M-2 stale server hello refused"),
    ("pqgrid/e2e/handshake.py", "        self._refuse_if_stale(\"resume reply\")               # DR-053",
     "        pass               # DR-053", "R M-2 stale resume reply refused"),
    ("pqgrid/e2e/handshake.py", "        self._refuse_if_stale(\"final message\")              # DR-053",
     "        pass              # DR-053", "R M-2 stale final message refused"),
    ("pqgrid/e2e/handshake.py", "        if (self._ch is None and self._rh is None) or self._attempt_fresh():",
     "        if True:", "R M-2 an old hello is not resent"),
    ("pqgrid/e2e/handshake.py", "                        and 0 <= age <= self.attempt_lifetime()):",
     "                        ):", "R M-2 a stored RH of unknown or great age is not resent after a reboot"),
    ("pqgrid/policy/validator.py", "        if not _is_ca_certificate(der):", "        if False:",
     "R M-3 ca_set holds CA certificates"),
    ("pqgrid/mqtt/device_node.py", "            self.c.replace_context(self.trust(p))",
     "            pass", "R M-3 trust follows the installed ca_set", ("tests/integration/test_ca_rollover.py",)),
    ("pqgrid/mqtt/utility_node.py", "        self.recompile_acl()                                         # L-1",
     "        pass                                         # L-1", "R L-1 an owed ACL recompile is retried"),
    ("pqgrid/mqtt/utility_node.py", "            self.alerts += [(did, p, dup) for _, p, dup in res.alerts]   # to the",
     "            pass   # to the", "R L-4 DF alerts delivered to the application"),
    ("pqgrid/mqtt/utility_node.py", "                self.ticket_reuse_alarms.append((did, self.clock()))",
     "                pass", "R L-9 clone alarm on a reused ticket"),
    ("pqgrid/mqtt/broker.py", "    if not (mq.isdigit() and 0 < int(mq)):", "    if False:", "R L-7 queue limit required"),
    ("pqgrid/mqtt/broker.py", "    elif glob[\"user\"] == \"root\" and not allow_root:", "    elif False:",
     "R L-7 root refused"),
    ("pqgrid/mqtt/utility_node.py",                  # 172: the key before the read right (the old order)
     "            self.recompile_acl()\n            self._send_zone_keys(zone)",
     "            self._send_zone_keys(zone)\n            self.recompile_acl()",
     "R join: read right before the new key"),
    # ---------------------------------------------------------------- Codex audit P1-2 (IMPLEMENTATION-ROADMAP §16)
    ("pqgrid/mqtt/utility_node.py", "            info.rc = mqtt.MQTT_ERR_SUCCESS                              # queued",
     "            pass                              # queued", "P1-2 a publish kept for the reconnect breaks nothing"),
    ("pqgrid/mqtt/utility_node.py", "        elif info.rc != mqtt.MQTT_ERR_SUCCESS:", "        elif False:",
     "P1-2 a publish the client did not queue is an error"),
    ("pqgrid/commands/utility.py", "                    self.store.unmark_sent(q, prev)                 # it never left",
     "                    pass                 # it never left", "P1-2 a command that never left is not counted as sent"),
    ("pqgrid/fota/publisher.py",
     "            elif all(a is True for a in answers):\n                pub.confirmed, pub.tokens = True, None",
     "            elif any(a is True for a in answers):\n                pub.confirmed, pub.tokens = True, None",
     "P1-2 confirmed only when every message was acknowledged"),
    ("pqgrid/fota/publisher.py", "            if False in answers:\n                pub.tokens = None",
     "            if False:\n                pub.tokens = None", "P1-2 a refused message un-does the publication"),
    ("pqgrid/mqtt/utility_node.py", "        refused = reason_code.is_failure", "        refused = False",
     "P1-2 a refusing PUBACK is recorded"),
    ("pqgrid/mqtt/utility_node.py", "                self.publisher.retry(self._fota_out)",
     "                pass", "P1-2 an unconfirmed artifact is published again"),
    ("pqgrid/persistence/utility_db.py", "                         int(retained is not None and retained.confirmed)))",
     "                         0))", "P1-2 confirmation is durable"),
    ("pqgrid/fota/publisher.py", "            if pub.tried_at is not None and now - pub.tried_at < self.retry_every_s:",
     "            if False:", "P1-2 retries are rate-limited"),
    ("pqgrid/fota/publisher.py", "            if pub.confirmed or pub.tokens is not None or not self.valid(pub.artifact):",
     "            if pub.confirmed or pub.tokens is not None:", "P1-2 a retry never resurrects an invalid artifact"),
    # ---------------------------------------------------- Codex audit P0-1, P1-1, P1-3, B, C (IMPLEMENTATION-ROADMAP §16)
    ("pqgrid/fota/installer.py", "        self._reverify_recovered()\n        self._finish_interrupted_keyrevoke()",
     "        self._finish_interrupted_keyrevoke()", "P0-1 recovered artifacts re-verified at boot"),
    ("pqgrid/fota/installer.py", "            m = self._reverify(FIRMWARE, m)                                # P0-1",
     "            pass                                # P0-1", "P0-1 firmware re-verified before activation"),
    ("pqgrid/fota/installer.py", "        m = self._reverify(POLICY, m)                                      # P0-1",
     "        pass                                      # P0-1", "P0-1 policy re-verified before activation"),
    ("pqgrid/fota/installer.py", "            if kept != m:", "            if False:",
     "P0-1 the record must be the kept signed manifest"),
    ("pqgrid/fota/installer.py",
     "        cap = (self.flash.slot_size if m.type == FIRMWARE else self.flash.area_size) - SIGNED_RESERVE",
     "        cap = (self.flash.slot_size if m.type == FIRMWARE else self.flash.area_size)",
     "P0-1 capacity leaves room for the kept signed manifest"),
    ("pqgrid/registry.py",
     "        if old is not None and (old.dclass, old.e2e_pk, old.active) != (rec.dclass, rec.e2e_pk, rec.active):",
     "        if False:", "P1-1 the registry never overwrites a device"),
    ("pqgrid/pasr/tickets.py", "        if rec.provisioned_at and t.issued_at <= rec.provisioned_at:", "        if False:",
     "P1-1 tickets of the old record refused"),
    ("pqgrid/e2e/handshake.py",
     "        self.registry._reprovision(rec, self.now())\n        return self._drop_device(rec.device_id)",
     "        self.registry._reprovision(rec, self.now())\n        return 0", "P1-1 the old record's sessions end"),
    ("pqgrid/commands/utility.py",
     "            self.store.close(q, b\"UNKNOWN\" if q.sends else b\"CANCELLED\")\n            n += 1",
     "            n += 1", "P1-1 the old record's commands close"),
    ("pqgrid/persistence/utility_db.py", "        zones = self.zones.rotate_device(rec.device_id)",
     "        zones = []", "P1-1 the old record's zone keys rotate"),
    ("pqgrid/persistence/utility_db.py",
     "            with self.db.tx():\n                self.commands.cancel_device(rec.device_id)",
     "            if True:\n                self.commands.cancel_device(rec.device_id)",
     "P1-1 record and commands change in one transaction"),
    ("pqgrid/mqtt/utility_node.py",
     "        self._acl_due = True\n        self.recompile_acl()\n\n    def _send_zone_keys(self, zone: str) -> None:",
     "        pass\n\n    def _send_zone_keys(self, zone: str) -> None:", "P1-1 the ACL follows the new record"),
    ("pqgrid/persistence/utility_db.py", "            os.fchmod(fd, DB_MODE)", "            pass",
     "P1-3 an existing backup target is narrowed first"),
    ("pqgrid/persistence/utility_db.py",
     "        require_owner_only(path)                              # an existing file, or a restored backup",
     "        pass                              # an existing file, or a restored backup",
     "P1-3 a database readable by others is refused"),
    ("pqgrid/fota/installer.py", "        check_anchors(anchors)\n", "", "B exactly the two distinct anchors"),
    ("pqgrid/mqtt/guard.py", "            super().extend(items)\n            self._trim()", "            super().extend(items)",
     "C a bounded log stays bounded when extended"),
    ("pqgrid/mqtt/utility_node.py", "        self.telemetry: list[tuple[bytes, bytes]] = BoundedLog(INBOX_CAP)",
     "        self.telemetry: list[tuple[bytes, bytes]] = []", "C the telemetry inbox is bounded"),
    ("pqgrid/mqtt/utility_node.py", "        self.alerts: list[tuple[bytes, bytes, bool]] = BoundedLog(INBOX_CAP)",
     "        self.alerts: list[tuple[bytes, bytes, bool]] = []", "C the alert inbox is bounded"),
    # -------------------------------------------------------- second Codex review (IMPLEMENTATION-ROADMAP §16.7)
    ("pqgrid/e2e/handshake.py",
     "                or s.provisioned_at != rec.provisioned_at                              # … and its provisioning\n",
     "", "R2-2 a session of an earlier provisioning is not current"),
    ("pqgrid/commands/utility.py", "            if q.provisioned_at != prov:", "            if False:",
     "R2-2 a command of an earlier provisioning is closed"),
    ("pqgrid/e2e/handshake.py", "        if s.provisioned_at != rec.provisioned_at:                           # re-provisioned",
     "        if False:                           # re-provisioned", "R2-2 a handshake across a record change is refused"),
    ("pqgrid/e2e/handshake.py",
     "        if s is not None and s.provisioned_at != self.registry.get(who.encode()).provisioned_at:",
     "        if False:", "R2-2 an alert of an earlier provisioning gets a resync hint"),
    ("pqgrid/commands/utility.py",
     "        if s.provisioned_at != self.u.registry.get(s.device_id).provisioned_at:   # finding 2",
     "        if False:   # finding 2", "R2-2 a status ACK of an earlier provisioning is refused"),
    ("pqgrid/mqtt/utility_node.py", "            elif ok is False and self.n.commands.unsend(did, cmd_seq, sid):",
     "            elif False:", "R2-1 a refused command is not counted as sent"),
    ("pqgrid/mqtt/utility_node.py", "                self._send_commands(did)\n", "                pass\n",
     "R2-1 a refused command is sent again"),
    ("pqgrid/mqtt/utility_node.py", "            self._settle_commands()                                    # finding 1",
     "            pass                                    # finding 1", "R2-1 tick settles command PUBACKs"),
    ("pqgrid/fota/installer.py", "        if len(key) != 1 or key[0] not in (FIRMWARE, POLICY, KEYREVOKE):",
     "        if False:", "R2-3 a recovered record's key is one known type"),
    ("pqgrid/fota/installer.py", "                if len(have) != (m.chunk_count + 7) // 8:", "                if False:",
     "R2-3 a recovered bitmap has the right length"),
    ("pqgrid/persistence/utility_db.py", "        finally:\n            if rotated is not None:\n                rotated(zones)",
     "        finally:\n            pass", "R2-5 the new zone keys go out even if the change fails"),
    ("pqgrid/mqtt/utility_node.py", "        self.c.max_queued_messages_set(CLIENT_QUEUE_MAX)\n", "",
     "R2-6 paho's queue is bounded"),
    ("pqgrid/mqtt/utility_node.py",
     "        if len(self._unacked) > UNACKED_TRACKED:                         # finding 6: no unbounded tracking",
     "        if False:                         # finding 6: no unbounded tracking", "R2-6 the tracking is bounded"),
    ("pqgrid/commands/utility.py",
     "        if len(self.store.open_commands(device_id)) >= MAX_QUEUED_COMMANDS:         # finding 6: backpressure",
     "        if False:         # finding 6: backpressure", "R2-6 open commands per device are capped"),
    ("pqgrid/mqtt/device_node.py", "        self.events: list[tuple[str, bytes]] = BoundedLog(1000)",
     "        self.events: list[tuple[str, bytes]] = []", "R2-6 the device's event list is bounded"),
    # ---------------------------------------------------------------- follow-up items 1 and 2 (§16.8)
    ("pqgrid/mqtt/device_node.py",
     "        self.c.max_queued_messages_set(self._queue_bound)     # §16.8: bounded while the broker is down\n", "",
     "F-1 the device's paho queue is bounded"),
    ("pqgrid/mqtt/device_node.py",
     "            self.c.max_queued_messages_set(self._queue_cap())  # §16.8: the installed class's outbox.",
     "            pass  # §16.8: the installed class's outbox.", "F-1 the bound follows the class's outbox"),
    ("pqgrid/fota/publisher.py", "            self._send_removal(client, r)\n        return n",
     "            pass\n        return n", "F-2 an unacknowledged removal is sent again"),
    ("pqgrid/fota/publisher.py", "                    self._store_removal(r)                         # together",
     "                    pass                         # together", "F-2 a removal is durable before it is sent"),
    ("pqgrid/fota/publisher.py", "            if False in answers:\n                r.tokens = None",
     "            if False:\n                r.tokens = None", "F-2 a refused removal is sent again"),
    ("pqgrid/fota/publisher.py",
     "        cancelled = [r for r in self.removals if (r.key, r.version) == (key, art.manifest.version)]",
     "        cancelled = []", "F-2 a republish cancels its pending removal"),
    ("pqgrid/mqtt/utility_node.py", "        return all(i.is_published() for i in pending)",
     "        return all(i.is_published() for i in self._unacked)", "F-3 flush() checks a copy, not the live deque"),
    # ---------------------------------------------------------- third Codex review (IMPLEMENTATION-ROADMAP §16.10)
    ("pqgrid/registry.py", "        rec = replace(rec, provisioned_at=0 if old is None else old.provisioned_at)\n", "",
     "R3-1 add() keeps the provisioning generation"),
    ("pqgrid/registry.py", "max(int(now), old.provisioned_at + 1)", "int(now)", "R3-1 the generation only ever grows"),
    ("pqgrid/mqtt/utility_node.py", "        self._cmd_pubs: list = []", "        self._cmd_pubs: list = BoundedLog(2)",
     "R3-2 command tracking is never evicted"),
    ("pqgrid/mqtt/utility_node.py", "            else:\n                d.refused = early", "            else:\n                pass",
     "R3-2 a PUBACK before the registration is kept"),
    ("pqgrid/fota/installer.py", "            if dl.complete():                                          # chunk's bit",
     "            if False:                                          # chunk's bit",
     "R3-3 a complete download is finished at boot"),
    ("pqgrid/fota/publisher.py", "        with self._atomic():                                       # ONE durable",
     "        if True:                                       # ONE durable",
     "R3-4 publication and removals in one transaction"),
    ("pqgrid/fota/installer.py", "            if admit:\n                self._admit(kept, n)",
     "            if False:\n                pass", "R3-5 recovered artifacts pass the admission checks"),
    ("pqgrid/persistence/utility_db.py", "        self._check_reprovision(rec)                       # third review",
     "        pass                       # third review", "R3-6 re-provisioning is checked before any side effect"),
    ("pqgrid/mqtt/device_node.py", "\n                                               or self._queue_bound < self._queue_cap())",
     ")", "R3-7 a grown queue bound makes the connection stale"),
]


ROOT = "/src"
TESTS = ["tests/unit", "tests/security"]          # the in-process suite: every mutant runs it


def run(i, mut):
    """KILLED only when the suite ran and a test FAILED (pytest exit code 1). Any other non-zero exit (a crash at
    import or collection, a usage error, an interrupted run) is ERROR: the mutant was not killed by a test."""
    path, old, new, name = mut[:4]
    extra = list(mut[4]) if len(mut) > 4 else []   # broker tests for checks only a real broker can exercise
    work = tempfile.mkdtemp()
    for d in ("pqgrid", "tests"):
        shutil.copytree(f"{ROOT}/{d}", f"{work}/{d}", ignore=shutil.ignore_patterns("__pycache__"))
    shutil.copy(f"{ROOT}/pytest.ini", work)
    src = open(f"{work}/{path}").read()
    n = src.count(old)
    if n != 1:
        shutil.rmtree(work)
        return f"{i:3d} BADPATTERN({n}) {name}"
    open(f"{work}/{path}", "w").write(src.replace(old, new))
    r = subprocess.run([sys.executable, "-m", "pytest", "-o", "addopts=", "-q", "-x", "-p", "no:cacheprovider",
                        *TESTS, *extra], cwd=work, capture_output=True, text=True, timeout=1800,
                       env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"})
    shutil.rmtree(work)
    last = r.stdout.strip().splitlines()[-1] if r.stdout.strip() else r.stderr[-200:]
    verdict = {0: "SURVIVED", 1: "KILLED  "}.get(r.returncode, "ERROR   ")
    return f"{i:3d} {verdict} {name}{' [+broker]' if extra else ''}   [{last}]"


if __name__ == "__main__":
    args = sys.argv[1:]
    if args[:1] == ["--root"]:                    # the source tree (default /src; /app inside the test image)
        ROOT, args = args[1], args[2:]
    if args[0] == "sel":                          # mutation_check.py [--root R] sel 1,9,10 <slice> <nslices>
        chosen = [int(x) for x in args[1].split(",")]
        k, n = int(args[2]), int(args[3])
        for j, i in enumerate(chosen):
            if j % n == k:
                print(run(i, M[i]), flush=True)
    else:                                         # mutation_check.py [--root R] <slice> <nslices>
        k, n = int(args[0]), int(args[1])
        for i, mut in enumerate(M):
            if i % n == k:
                print(run(i, mut), flush=True)
